config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :create] do
    resources :tweets, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  end

  get 'run_migrations', to: 'migrations#run'

  # Signup and login routes
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  # User
  get 'profile', to: 'profiles#show', as: 'profile'

  # Tweets routes 
  resources :tweets, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  get 'tweets/:id/edit', to: 'tweets#edit'

  # Defines the root path route ("/")
  root "pages#landingpage"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweet.rb
# app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  validates :status, presence: true
end

# app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :tweets
  validates :email, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord  
  has_secure_password

  has_many :tweets, dependent: :destroy

  validates :name, presence: true
  validates :graveyard, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/migrations_controller.rb
class MigrationsController < ApplicationController
  def run
    begin
      ActiveRecord::MigrationContext.new(
        ActiveRecord::Migrator.migrations_paths,
        ActiveRecord::SchemaMigration
      ).migrate

      render plain: "Migrations ran successfully."
    rescue => e
      render plain: "Error running migrations: #{e.message}"
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = User.find(session[:user_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email])

    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to tweets_path, notice: 'Logged in successfully'
    else
      flash.now[:alert] = 'Invalid credentials'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged out successfully'
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user, only: [:create, :edit, :update, :destroy]

  def index
    @tweet = Tweet.new
    @tweets = Tweet.order(created_at: :desc).limit(20)
  end

  def show
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user_id = session[:user_id]

    if @tweet.save
      respond_to do |format|
        format.turbo_stream
        format.html {redirect_to tweets_path, notice: 'Tweet published.'}
      end
    else
      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.replace("new_tweet", partial: "tweets/form", locals: { tweet: @tweet})}
        format.html { render :new }  
    end
  end
end

  def edit
    @tweet = Tweet.find(params[:id])
    render :edit    
  end

  def update
    @tweet = Tweet.find(params[:id])
    #respond_to do |format|
      if @tweet.update(tweet_params)
        redirect_to tweets_path, notice: 'Tweet updated.'
        #format.html { redirect_to(@tweet, notice => 'Post updated')  }
      else
        render :edit

        #format.html{ render :action => 'edit' }
      end
    #end

    #if @tweet.update(tweet_params)
     # redirect_to tweets_path, notice: 'Tweet was successfully updated.'
    #else
    #  render :edit
    #end
  end

  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_path, notice: 'Tweet deleted.' }
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@tweet) }
    end
    # redirect_to tweets_path, notice: 'Tweet was successfully destroyed.'
  end

  private

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  def tweet_params
    params.require(:tweet).permit(:status, :user_id)
  end

  def authenticate_user
    redirect_to login_path, alert: 'You must be logged in to perform this action' unless session[:user_id]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end  

  def create
    @user = User.new(user_params)
    if @user.save
      Rails.logger.info "User successfully created: #{@user.inspect}"
      session[:user_id] = @user.id
      flash[:notice] = 'User was successfully created'
      redirect_to '/'
    else
      Rails.logger.error "User creation failed: #{@user.errors.full_messages}"
      render :new
    end
  end

  def show
    @user = User.find(session[:user_id])
  end

  private
  def user_params
    params.require(:user).permit(:name, :graveyard, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/migrations_helper.rb
module MigrationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZombieTwitter</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <% if flash[:notice] %>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= flash[:notice] %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      <% flash.discard(:notice) %>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <%= flash[:alert] %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      <% flash.discard(:alert) %>
    <% end %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script>
      document.addEventListener('DOMContentLoaded', (event) => {
        setTimeout(() => {
          let alert = document.querySelector('.alert');
          if (alert) {
            alert.classList.remove('show');
            alert.classList.add('fade');
            setTimeout(() => {
              alert.remove();
            }, 150); // Matches Bootstrap's fade transition duration
          }
        }, 3000); // 3 seconds before auto dismissing
      });
    </script>
  </body>
</html>

app/views/pages/landingpage.html.erb
<div class="container text-center">
  <div class="row">
    <div class="col">
      <h2>Twitter for Zombies</h2>
      <div class="btn-group" role="group">
        <%= button_to 'Sign Up', signup_path, method: :get, class: 'btn btn-secondary' %>
        <%= button_to 'Login', login_path, method: :get, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<!-- app/views/profiles/show.html.erb -->
<div class="container">
  <h2 class="mb-4">Profile</h2>
  <%= link_to "Home", tweets_path, class: 'btn btn-secondary mb-4' %>
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">User Information</h5>
      <ul class="list-unstyled">
        <li><strong>Name:</strong> <%= @user.name %></li>
        <li><strong>Graveyard:</strong> <%= @user.graveyard %></li>
        <li><strong>Email:</strong> <%= @user.email %></li>
      </ul>
    </div>
  </div>
</div>

app/views/tweets/destroy.turbo_stream.erb
<%= turbo_stream.remove @tweet %>

app/views/tweets/edit.html.erb
<%= form_with(model: @tweet, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :status %>
    <%= form.text_field :status, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.submit "Update Tweet", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tweets/index.html.erb
<div class="container text-center">
  <div class="row">
    <div class="col">
      <h2>What's happening around the world</h2>
      <% if session[:user_id] %>
        <%= link_to User.find(session[:user_id]).name, profile_path(:user_id), class: "user" %>
      <% else %>
        <%= button_to 'Login', login_path %>
      <% end %>
      <p>Not you? <%= button_to 'Logout', logout_path, method: :delete %> </p>
    </div>
    <div class="col">
      <%= form_with(model: @tweet, local: true) do |form| %>
        <div class="form-group">
          <%= form.text_area :status, placeholder: "Tweet something", class: "form-control", autocomplete: 'off' %>
          <%= form.hidden_field :user_id, value: session[:user_id] %>
        </div>
        <div class="form-group">
          <%= form.submit "Post Tweet", class: "btn btn-primary" %>
        </div>
      <% end %>
      <ul class="list-group">
        <% @tweets.each do |tweet| %>
          <li class="list-group-item">
            <%= "@" + tweet.user.name %><br>
            <%= tweet.status %>
            <% if tweet.user_id == session[:user_id] %>
              <div class="d-flex">
                <%= link_to "Edit", edit_tweet_path(tweet), class: 'btn btn-secondary me-2' %>
                <%= button_to "Delete", tweet, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %>
              </div>
              <!--<%= link_to "Delete", tweet_path(tweet), class: "btn btn-danger btn-xs pull-right", data: { turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>
            <%= button_to "delete", tweet_path(tweet), class: "item", method: :delete, data: { turbo_confirm: 'operate.delete_confirm?'} %>
            <%= button_to 'Destroy', @tweet, method: :delete, form: {data: {turbo_confirm: 'Are you sure?'}} %>
            <%= button_to tweet_path(tweet), method: :delete, data: {confirm: 'Are you sure?'} do %>-->
            <% end %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/tweets/show.html.erb
<h1>Tweet</h1>
<p>
  <strong>Status:</strong>
  <%= @tweet.status %>
</p>

app/views/users/new.html.erb
<p>Sign up</p>
<%= form_with model: @user, local: true, html: { autocomplete: "off" } do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name, placeholder: "Name" %>
  </div>
  <div>
    <%= form.label :graveyard %>
    <%= form.text_area :graveyard, placeholder: "Graveyard" %>
  </div>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email, placeholder: "Email" %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password, placeholder: "Password" %>
  </div>
  <div>
    <%= form.submit "Register" %>
  </div>
<% end %>
<%= link_to 'Login', login_path %>